### 회원가입 (토큰 필요 없음)
POST http://localhost:8080/api/users/signup
Content-Type: application/json

{
  "email": "test2@test.com",
  "password": "admin1234!",
  "nickname": "test2"
}

### 이메일 중복확인
POST http://localhost:8080/api/users/check/email
Content-Type: application/json

{
  "email": "test@test.com"
}

### 닉네임 중복확인
POST http://localhost:8080/api/users/check/nickname
Content-Type: application/json

{
  "nickname": "t!est1111111111"
}


### 로그인
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "email": "test2@test.com",
  "password": "admin1234!"
}

### 회원정보 수정
PATCH http://localhost:8080/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QHRlc3QuY29tIiwiaWQiOjExLCJuaWNrbmFtZSI6InRlc3QiLCJyb2xlIjoiUk9MRV9BRE1JTiIsImlhdCI6MTc0NDcwMzY2MSwiZXhwIjoxNzQ0NzkwMDYxfQ.Pfpaw0_AFkV_4_peWl0CY1qegJBs_x-cqlIQLt_pFDs
Content-Type: application/json

{
  "nickname": "사용자",
  "password": "admin1234!"
}

### 회원탈퇴
DELETE http://localhost:8080/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0NEB0ZXN0LmNvbSIsImlkIjo3LCJuaWNrbmFtZSI6Iu2FjOyKpO2KuOycoOyggDQiLCJyb2xlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzQ0MjYwMDMxLCJleHAiOjE3NDQzNDY0MzF9.GdMYlSTwipgWRuTzzULMw8wCy12hzOYDaTG0HOBXcsU

### 게시글 등록
POST http://localhost:8080/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBhZG1pbi5jb20iLCJpZCI6MTAsIm5pY2tuYW1lIjoiQWRtaW4iLCJyb2xlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzQ0NjEzMDMxLCJleHAiOjE3NDQ2OTk0MzF9.YdPPce2_DWmbm5OvyRXIYkSFORrRXn2csQjye-NkGH0
Content-Type: application/json

{
  "title": "어드민이 쓴 글1",
  "content": "어드민이 쓰는 글입니다."
}

### 게시글 목록 조회
GET http://localhost:8080/api/posts

### 게시글 조건 조회
GET http://localhost:8080/api/posts?title=&nickname=&date=&page=2&size=10&sort=createdAt&direction=DESC



### 게시글 단일 조회
GET http://localhost:8080/api/posts/1


### 게시글 수정
PUT http://localhost:8080/api/posts/3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QHRlc3QuY29tIiwiaWQiOjExLCJuaWNrbmFtZSI6InRlc3QiLCJyb2xlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzQ0MzU4MzA0LCJleHAiOjE3NDQ0NDQ3MDR9.P4lUK5RT71XKTlGhG4MS7x0J-2RqKaLolKE-QigD7XY
Content-Type: application/json

{
  "title": "테스터가 쓴 글1",
  "content": "테스터가 쓰는 글1입니다."
}

### 게시글 삭제
DELETE http://localhost:8080/api/posts/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QHRlc3QuY29tIiwiaWQiOjExLCJuaWNrbmFtZSI6InRlc3QiLCJyb2xlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzQ0MzU4MzA0LCJleHAiOjE3NDQ0NDQ3MDR9.P4lUK5RT71XKTlGhG4MS7x0J-2RqKaLolKE-QigD7XY


### 댓글 등록
POST http://localhost:8080/api/comments/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBhZG1pbi5jb20iLCJpZCI6MTAsIm5pY2tuYW1lIjoiQWRtaW4iLCJyb2xlIjoiUk9MRV9BRE1JTiIsImlhdCI6MTc0NDcwMzU4MywiZXhwIjoxNzQ0Nzg5OTgzfQ.F7vhdPb2Qft956AtDTg5Vzt5-hpcNnKvyBetvm3EWIo
Content-Type: application/json

{
  "content": "테스터가 쓰는 댓글 2입니다."
}

### 댓글 조회
GET http://localhost:8080/api/comments/post/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBhZG1pbi5jb20iLCJpZCI6MTAsIm5pY2tuYW1lIjoiQWRtaW4iLCJyb2xlIjoiUk9MRV9BRE1JTiIsImlhdCI6MTc0NDcwMzU4MywiZXhwIjoxNzQ0Nzg5OTgzfQ.F7vhdPb2Qft956AtDTg5Vzt5-hpcNnKvyBetvm3EWIo


### 댓글 수정

PUT http://localhost:8080/api/comments/4
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QHRlc3QuY29tIiwiaWQiOjExLCJuaWNrbmFtZSI6InRlc3QiLCJyb2xlIjoiUk9MRV9BRE1JTiIsImlhdCI6MTc0NDcwMzY2MSwiZXhwIjoxNzQ0NzkwMDYxfQ.Pfpaw0_AFkV_4_peWl0CY1qegJBs_x-cqlIQLt_pFDs
Content-Type: application/json

{
  "content": "테스터가 수정한 댓글 입니다."
}

### 댓글 삭제
DELETE http://localhost:8080/api/comments/4
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QHRlc3QuY29tIiwiaWQiOjExLCJuaWNrbmFtZSI6InRlc3QiLCJyb2xlIjoiUk9MRV9BRE1JTiIsImlhdCI6MTc0NDcwMzY2MSwiZXhwIjoxNzQ0NzkwMDYxfQ.Pfpaw0_AFkV_4_peWl0CY1qegJBs_x-cqlIQLt_pFDs

### 게시글 삭제 (관리자)
DELETE http://localhost:8080/api/admin/posts/16
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBhZG1pbi5jb20iLCJpZCI6MTAsIm5pY2tuYW1lIjoiQWRtaW4iLCJyb2xlIjoiUk9MRV9BRE1JTiIsImlhdCI6MTc0NDcwMzU4MywiZXhwIjoxNzQ0Nzg5OTgzfQ.F7vhdPb2Qft956AtDTg5Vzt5-hpcNnKvyBetvm3EWIo

### 댓글 삭제 (관리자)
DELETE http://localhost:8080/api/admin/comments/7
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBhZG1pbi5jb20iLCJpZCI6MTAsIm5pY2tuYW1lIjoiQWRtaW4iLCJyb2xlIjoiUk9MRV9BRE1JTiIsImlhdCI6MTc0NDcwMzU4MywiZXhwIjoxNzQ0Nzg5OTgzfQ.F7vhdPb2Qft956AtDTg5Vzt5-hpcNnKvyBetvm3EWIo

### 계정 삭제 (관리자)
DELETE http://localhost:8080/api/admin/users/19
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBhZG1pbi5jb20iLCJpZCI6MTAsIm5pY2tuYW1lIjoiQWRtaW4iLCJyb2xlIjoiUk9MRV9BRE1JTiIsImlhdCI6MTc0NDcwMzU4MywiZXhwIjoxNzQ0Nzg5OTgzfQ.F7vhdPb2Qft956AtDTg5Vzt5-hpcNnKvyBetvm3EWIo

### 계정 잠금 해지 (관리자)
PATCH  http://localhost:8080/api/admin/users/11/unlock
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBhZG1pbi5jb20iLCJpZCI6MTAsIm5pY2tuYW1lIjoiQWRtaW4iLCJyb2xlIjoiUk9MRV9BRE1JTiIsImlhdCI6MTc0NDcwMzU4MywiZXhwIjoxNzQ0Nzg5OTgzfQ.F7vhdPb2Qft956AtDTg5Vzt5-hpcNnKvyBetvm3EWIo

### 계정 잠금 해지 (유저)
PATCH  http://localhost:8080/api/admin/users/11/unlock
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QHRlc3QuY29tIiwiaWQiOjExLCJuaWNrbmFtZSI6InRlc3QiLCJyb2xlIjoiUk9MRV9BRE1JTiIsImlhdCI6MTc0NDcwMzY2MSwiZXhwIjoxNzQ0NzkwMDYxfQ.Pfpaw0_AFkV_4_peWl0CY1qegJBs_x-cqlIQLt_pFDs



###
# 관리자 토큰
# eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBhZG1pbi5jb20iLCJpZCI6MTAsIm5pY2tuYW1lIjoiQWRtaW4iLCJyb2xlIjoiUk9MRV9BRE1JTiIsImlhdCI6MTc0NDcwMzU4MywiZXhwIjoxNzQ0Nzg5OTgzfQ.F7vhdPb2Qft956AtDTg5Vzt5-hpcNnKvyBetvm3EWIo
# 유저 토큰
# eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QHRlc3QuY29tIiwiaWQiOjExLCJuaWNrbmFtZSI6InRlc3QiLCJyb2xlIjoiUk9MRV9BRE1JTiIsImlhdCI6MTc0NDcwMzY2MSwiZXhwIjoxNzQ0NzkwMDYxfQ.Pfpaw0_AFkV_4_peWl0CY1qegJBs_x-cqlIQLt_pFDs