spring:
  # error:
  #   whitelabel:
  #     enabled: false
  #   path: /error
  #   include-message: always
  #   include-binding-errors: always
  application:
    name: board
  thymeleaf:
    cache: false # 개발 환경에서는 캐시를 비활성화
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    content-type: text/html
    enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
  mvc:
    pathmatch:
      matching-strategy: path-pattern-parser # 또는 ant-path-matcher
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mapper/**.xml
  type-aliases-package: com.example.board.domain
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: secret-key-should-be-very-long-and-secure-at-least-256-bits
  expiration: 86400000 # 24시간
  header: Authorization
  prefix: Bearer
